spring:
  application.name: mongodb-demo
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: amigoscode
      port: 27017
      host: localhost
      auto-index-creation: true